services:
  - type: web
    name: tgbot-admin
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.18.1
      - key: NPM_VERSION
        value: 10.8.2
